# Generated by Django 4.1.3 on 2022-11-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
