# Generated by Django 4.1.3 on 2022-11-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0006_hero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='teams',
            new_name='team',
        ),
    ]
