# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0007_rename_teams_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='hero_player_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('hero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esports_app.hero')),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esports_app.match')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esports_app.player')),
            ],
        ),
    ]
