# Generated by Django 4.1.3 on 2022-11-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0008_hero_player_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esports_app.match')),
            ],
        ),
    ]
