# Generated by Django 4.1.3 on 2022-12-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esports_app', '0009_match_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='esports_app.match')),
            ],
        ),
        migrations.DeleteModel(
            name='Match_scores',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to='esports_app.match_score'),
        ),
    ]
